Algoritmo "Processamento de dados"

Var
     a : real
     b : inteiro
     x,y : inteiro

Inicio
      a <- 5.3
      b <- a
// vai dar errado a de cima pq b nao pode ter valores nao inteiros
      b <- Int(a)
// vai dar pq so vai pegar a parte inteira
      escreval (a)
      escreval (b)
escreval
escreval
escreval
       x <- 5
       y <- x * 2
       escreval (x)
       escreval (y)
       
       

Fimalgoritmo