Algoritmo "semnome"

Var
      x , soma : inteiro


Inicio

       escreva("Qual o valor de X?")
       leia(x)

       enquanto x <> 0 faca

                se x % 2 <> 0 entao
                   x <- x +1
                fimse

                soma <- 5 * x + 20
                escreval("soma:", soma)
                
                escreval("Qual o valor de X?")
                leia(x)

       fimenquanto
       
       
       
       

Fimalgoritmo