Algoritmo "semnome"

Var
    n, i : inteiro
    a , b ,c ,media: real

Inicio
    escreval("Quantas notas serao digitadas")
    leia (n)
    
         para i de 1 ate n faca
         
          escreval("digite as notas")
          leia(a)
          leia(b)
          leia(c)
                 media <- (a * 2 + b * 3 + c * 5) / 10
                 
            escreval ("nota media ", media:4:1)
         fimpara
                 

Fimalgoritmo