Algoritmo "semnome"

Var
    x , y : inteiro


Inicio
     escreval("Digite 2 numeros: ")
     leia(X)
     leia(y)
     
     enquanto x <> y faca
              se x > y entao
                 escreval("Decrescente!")
              senao
                 escreval("Crescente!")
              fimse
        escreval("Digite outros 2 numeros:")
        leia(x)
        leia(y)

     fimenquanto
     
              
     
     
     
     
     
     
Fimalgoritmo