Algoritmo "terreno dever"

Var
   largura, comprimento, metroQuadrado, area, preco : real
   



Inicio
      escreval("Qual a largura do terreno?")
      leia(largura)
      escreval("Qual o comprimento do terreno?")
      leia(comprimento)
      escreval("Quanto custa o metro quadrado da região?")
      leia(metroQuadrado)
      
      area <- largura * comprimento
      preco <- area * metroQuadrado
      
      escreval("O preço do terreno é de:", preco)
      

      





Fimalgoritmo